{
  "comments": [
    {
      "key": {
        "uuid": "2bac58f8_a738b7d1",
        "filename": "dcipipeline/main.py",
        "patchSetId": 2
      },
      "lineNbr": 372,
      "author": {
        "id": 648
      },
      "writtenOn": "2021-03-19T23:34:02Z",
      "side": 1,
      "message": "does log.error interrupt the flow of the code? I don\u0027t think it does, this would print an error then continue with the .update on the next line",
      "revId": "512b6e4bfc700d62ab9ca6c97e22c9f3219c2af5",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0",
      "unresolved": true
    }
  ]
}